[package]
name = "floneum-workspace"
version = "0.1.0"
edition = "2021"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"

[dependencies]

[patch.crates-io]
dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus-rsx = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "improved-signals" }

[workspace]
members = [
    "models/rbert",
    "models/kalosm-llama",
    "models/rphi",
    "models/rwhisper",
    "models/rwuerstchen",
    "models/segment-anything-rs",
    "models/kalosm-ocr",
    "interfaces/kalosm",
    "interfaces/kalosm-language",
    "interfaces/language-model",
    "interfaces/kalosm-sample",
    "interfaces/kalosm-vision",
    "interfaces/kalosm-sound",
    "interfaces/kalosm-streams",
    "interfaces/kalosm-learning",
    "interfaces/kalosm-learning-macro",
    "floneum/floneum",
    "floneum/plugin",
    "floneum/rust_adapter",
    "floneum/rust_macro",
    "floneum/floneumite",
    "floneum/floneum-cli",
    "floneum/plugins/generate_text",
    "floneum/plugins/generate_structured_text",
    "floneum/plugins/format",
    "floneum/plugins/search",
    "floneum/plugins/embedding",
    "floneum/plugins/embedding_db",
    "floneum/plugins/add_embedding",
    "floneum/plugins/search_engine",
    "floneum/plugins/write_to_file",
    "floneum/plugins/read_from_file",
    "floneum/plugins/if_statement",
    "floneum/plugins/contains",
    "floneum/plugins/python",
    "floneum/plugins/find_node",
    "floneum/plugins/click_node",
    "floneum/plugins/node_text",
    "floneum/plugins/type_in_node",
    "floneum/plugins/navigate_to",
    "floneum/plugins/find_child_node",
    "floneum/plugins/get_article",
    "floneum/plugins/read_rss",
    "floneum/plugins/split",
    "floneum/plugins/join",
    "floneum/plugins/slice",
    "floneum/plugins/add_to_list",
    "floneum/plugins/new_list",
    "floneum/plugins/length",
    "floneum/plugins/more_than",
    "floneum/plugins/less_than",
    "floneum/plugins/equals",
    "floneum/plugins/and",
    "floneum/plugins/or",
    "floneum/plugins/not",
    "floneum/plugins/add",
    "floneum/plugins/subtract",
    "floneum/plugins/multiply",
    "floneum/plugins/divide",
    "floneum/plugins/power",
    "floneum/plugins/number",
    "floneum/plugins/string",
    "interfaces/kalosm-common",
    "floneum/plugins/calculate",
]

[workspace.dependencies]
candle-core = { version = "=0.4.1" }
candle-nn = { version = "=0.4.1" }
candle-transformers = { version = "=0.4.1" }
candle-datasets = { version = "=0.4.1" }
kalosm = { path = "./interfaces/kalosm", version = "0.2.1" }
kalosm-sample = { path = "./interfaces/kalosm-sample", version = "0.2.1" }
kalosm-common = { path = "./interfaces/kalosm-common", version = "0.1.0" }
kalosm-language-model = { path = "./interfaces/language-model", version = "0.2.1" }
kalosm-streams = { path = "./interfaces/kalosm-streams", version = "0.2.1" }
kalosm-language = { path = "./interfaces/kalosm-language", version = "0.2.1" }
kalosm-sound = { path = "./interfaces/kalosm-sound", version = "0.2.1" }
kalosm-vision = { path = "./interfaces/kalosm-vision", version = "0.2.1" }
kalosm-learning = { path = "./interfaces/kalosm-learning", version = "0.2.1" }
kalosm-learning-macro = { path = "./interfaces/kalosm-learning-macro", version = "0.2.1" }
rphi = { path = "./models/rphi", version = "0.2.1" }
rbert = { path = "./models/rbert", version = "0.2.1" }
kalosm-llama = { path = "./models/kalosm-llama", version = "0.2.1" }
rwhisper = { path = "./models/rwhisper", version = "0.2.1" }
rwuerstchen = { path = "./models/rwuerstchen", version = "0.2.1" }
segment-anything-rs = { path = "./models/segment-anything-rs", version = "0.2.1" }
kalosm-ocr = { path = "./models/kalosm-ocr", version = "0.2.1" }
llm-samplers = "=0.0.7"

[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
lto = true
opt-level = 3
debug = false
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
