[package]
name = "kalosm-streams"
version = "0.1.0"
edition = "2021"
description = "A set of streams for pretrained models in Kalosm"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]

[dependencies]
futures-util = "0.3.28"
anyhow = "1.0.71"
tracing = "0.1.37"
pin-project = "1"
tokio = { version = "1.28.1", features = ["full"] }
