[package]
name = "kalosm-sound"
version = "0.2.1"
edition = "2021"
description = "A set of pretrained audio models "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "whisper"]

[dependencies]
anyhow = "1.0.70"
cpal = "0.15.1"
itertools = "0.10.5"
rand = "0.8.5"
ringbuf = "0.3.2"
webrtc-vad = "0.4"
candle-core.workspace = true
candle-nn.workspace = true
candle-transformers.workspace = true
byteorder = "1.4.3"
hf-hub = "0.3.1"
tokenizers = "0.14.0"
serde_json = "1.0.107"
hound = "3.5"
rodio = "0.17.1"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
ringbuffer = "0.15.0"
futures-util = "0.3.28"
async-trait = "0.1.73"
kalosm-streams.workspace = true
rwhisper.workspace = true

[features]
metal = ["candle-core/metal", "rwhisper/accelerate", "rwhisper/metal"]
cuda = ["candle-core/cuda", "rwhisper/cuda", "rwhisper/cudnn"]
mkl = ["candle-core/mkl", "rwhisper/mkl"]
